server:
 port: 7001
spring:
 application:
  name: server-config
 profiles:
  active: native
 cloud:
  config:
   server:
    git:
     uri: https://github.com/MyLobin/Java-Learning/
     searchPaths: microservice/config-repo
     username: mylobin
     password: password