server:
 port: 5555
spring:
 application:
  name: zuul-gateway
zuul:
 routes:
  api-a:
   path: /api-a/**
   serviceId: ACTIVITIDEMO
  api-b:
   path: /api-b/**
   serviceId: REBBON-EUREKA
  api-a-url:
   path: /api-a-url/**
   url: http://localhost:8088/
eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:1111/eureka/