spring:
    application:
        name: demo
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.31.102/ssm
    activemq:
        broker-url: tcp://localhost:61616
        user: admin
        password: secret
        

rabbitmq:
    host: 192.168.31.102
    port: 5672
    username: guest
    password: guest
    
